/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rtrk_pnrs1_ra38_2014_CalculateNative */

#ifndef _Included_rtrk_pnrs1_ra38_2014_CalculateNative
#define _Included_rtrk_pnrs1_ra38_2014_CalculateNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rtrk_pnrs1_ra38_2014_CalculateNative
 * Method:    getPercentage
 * Signature: (II)F
 */
JNIEXPORT jfloat JNICALL Java_rtrk_pnrs1_ra38_12014_CalculateNative_getPercentage
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
